# Generated by Django 6.0.3 on 2026-03-08 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, editable=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=256)),
                ('kind', models.CharField(choices=[('PERSON', 'Person'), ('COMPANY', 'Company'), ('ADDRESS', 'Address'), ('ACCOUNT', 'Account')], db_index=True, max_length=32)),
                ('country', models.CharField(blank=True, db_index=True, default='', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, editable=False, unique=True)),
                ('rel_type', models.CharField(choices=[('OWNS', 'Owns'), ('DIRECTOR_OF', 'Director Of'), ('SHARES_ADDRESS_WITH', 'Shares Address With'), ('TRANSFERRED_TO', 'Transferred To')], db_index=True, max_length=64)),
                ('weight', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='core.entity')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='core.entity')),
            ],
        ),
    ]
